### ISSUE TITLE
Vaccination target may be inaccurate

### ISSUE THREAD

**Issue by ThePraeceps** [mishajw/vaxtldr.uk#15]
Sky news reports the vaccination target being very different from your current graph.

https://news.sky.com/story/covid-19-uk-breaks-daily-jab-record-with-more-than-660-000-vaccine-doses-administered-12250729
https://www.bbc.co.uk/news/health-55274833

In addition if they had hit the target I'd expect more of the age groups to be filled.

**Comment by ChrisLane** [comment]
I haven't double checked the actual % for the 15th April target but I know that the value will be different to what is reported in those articles since vaxtldr.uk is only for presenting data for England and not the UK as a whole.

I suspect the 37.4% used by this site is an estimate of the over-50s population and doesn't include the additional categories such as people with underlying health conditions.

**Comment by ThePraeceps** [comment]
Yeah that makes sense - the BBC article says the target is about 32 million for the priority groups - you could use the population percentage in England (84.3%) to get a target of ~27 million which should include underlying health conditions.

**Comment by mishajw** [comment]
Thanks for spotting that, you're right - this misses ~6 million key workers & critically vulnerable (see [table 2](https://www.gov.uk/government/publications/uk-covid-19-vaccines-delivery-plan/uk-covid-19-vaccines-delivery-plan)). Fix coming up
